version: '3'
services:
  app:
    build: .
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - APP_KEY=mW05cR0lsyP3MtggpnNawWhN3gfAspQF
      - DATABASE_URL=mysql://root:root@mysql:3306/db_flashcards
    depends_on:
      - mysql
    command: npm run start
    stdin_open: true
    tty: true
    restart: always
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_flashcards
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
