# Creation date : 11.02.2025
# Created by : Alban Segalen
# Description : creates 2 containers: AdonisJS App, MySQL
#
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_app
    restart: always
    ports:
      - '3333:3333'
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      APP_KEY: mW05cR0lsyP3MtggpnNawWhN3gfAspQF
      NODE_ENV: development
      SESSION_DRIVER: cookie
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "echo 'Attente du démarrage de PostGres...' && sleep 10 && echo 'Exécution des migrations...' && node ace migration:run --force && echo 'Exécution des seeds...' && node ace db:seed && npm run build && cd build && npm ci --omit='dev' && node bin/server.js"
